@startgantt
Project starts 2024-03-01
printscale weekly

TITLE ALMA implementation @ SDUB
header Page Header
footer 2024-03-05/ErBa

'https://raw.githubusercontent.com/BIT-SDUB/ALMA/main/implentation/timeline.puml

' start up
[Symphony live] starts 2024-03-01 and ends 2024-12-17
[Symphony closing period (duedate=2025-03-01)] starts 2024-11-01 and ends 2025-02-15

[BIT analytics] starts 2024-03-01 and ends 2024-05-01 and is 5% complete

'>>> Exlibris
'• Onboarding May and June 2024
[Onboarding] starts 2024-05-01 and ends 2024-06-30
'
'[Vaccation] starts 2024-07-01 and ends 2024-07-30
'July is closed
2024-07-01 to 2024-07-30 is closed
'
'• Kick-off: early August 2024
[Kick-off] starts 2024-08-01 and ends 2024-11-30
'
'• Test load start: mid-September 2024
[Test load] starts 2024-09-15 and lasts 15 days
'[Test load] lasts 15 days
'
'• Cutover start: 1st December 2024
[Cutover start] starts 2024-12-01
[Cutover start] lasts 15 days
'
'• Go live: 17th December 2024
[Go live] happens 2024-12-17
[ALMA live] starts at [Symphony live]'s end

[ALMA live] starts 2024-12-17 and ends 2025-02-15
'[ALMA live] lasts 60 days
'• Transition to Support: by end of January 2025
[Transition to Support] happens 2025-01-31
'[ALMA live] starts at [Symphony live]'s end
[ALMA Support] starts 2025-01-31 and ends 2025-02-15
[ALMA Support] starts at [Transition to Support]'s end
'
'>>> Colors
  [Symphony live] is colored in Fuchsia/FireBrick
  [Symphony closing period] is colored in violet
'purple
  [ALMA live] is colored in GreenYellow/Green
  [ALMA Support] is colored in Olive
  
  [Onboarding] is colored in pink
  '
  [Test load] is colored in yellow
  [Cutover start] is colored in yellow
  [Kick-off] is colored in technology 
  ' dusted green
  [Vacation] is colored in gray
  [BIT analytics] is colored in SkyBlue
'<<< Colors

@endgantt
